# Generated by Django 3.1.3 on 2020-12-01 09:40

import core.utils.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge', 'create_plans'),
        ('feature', 'create_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='plan',
            field=models.ForeignKey(default=core.utils.utils.get_random_plan, on_delete=django.db.models.deletion.PROTECT, to='charge.plan'),
        ),
    ]
