# Generated by Django 3.1.3 on 2020-12-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', 'create_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='allow',
            field=models.BooleanField(default=True),
        ),
    ]
